<a href="https://colab.research.google.com/github/KevinCeda/-LinearAlgebra1T-2021-2022-/blob/main/Assignment4_CEDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Linear Algebra for ECE
##Laboratory 4: Matrices
 Now that you have a fundamental knowledge about Python, we'll try to look into greater dimensions.

##Objectives
At the end of this activity you will be able to:

    

*   Be familiar with matrices and their relation to linear equations.
*   Perform basic matrix operations.

*   Program and translate matrix equations and operations using Python.







##Discussion 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##Matrices
Matrices can be utilized to minimally compose and work with multiple linear equations, alluded to as an system of linear equations, simultaneously. Matrices and matrix multiplication reveal their fundamental provisions when identified with transformations or also known as linear maps.

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

##Declaring Matrices
Very much like in our previous lab activity, we'll address system of linear equations as a matrix. The elements or numbers in networks are known as the components of a matrix. These elements are ordered or arranged in columns and rows which structure the array construction of matrices. This can be reprsented just like the equation below. Whereas $A$ is a matrix consisting of elements denoted by $a_{i,j}$. Denoted by $i$ is the number of rows in the matrix while $j$ stands for the number of columns.
Do note that the $size$ of a matrix is $i\times j$.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

We already gone over some of the types of matrices but we'll further discuss them in this laboratory activity. Since you already know theorectically what are the shape,dimensions and size attributes of the matrices, we will do it in this platform.

In [2]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [3]:
A = np.array([
      [1, 2],
      [3, 10]        
])
describe_mat(A)

Matrix:
[[ 1  2]
 [ 3 10]]

Shape:	(2, 2)
Rank:	2



In [4]:
B = np.array([[
      [8, 2],
      [5, 4],
      [7, 7]        
]])
describe_mat(B)

Matrix:
[[[8 2]
  [5 4]
  [7 7]]]

Shape:	(1, 3, 2)
Rank:	3



In [5]:
G = np.array([
    [1,1],
    [2,2]
])
describe_mat(G)

Matrix:
[[1 1]
 [2 2]]

Shape:	(2, 2)
Rank:	2



In [6]:
H = np.array([1,2,3,4,5])
describe_mat(H)

Matrix:
[1 2 3 4 5]

Shape:	(5,)
Rank:	1



##Categorizing Matrices
Matrixes can be classified in a variety of ways.
One may be based on their shape, while the other could be based on their element values. 

**Row and Column Matrices**
In vector and matrix computations, row and column matrices are frequent.
They can also be used to represent the rows and columns of a larger vector space.
A single column or row is used to depict row and column matrices.


In [ ]:
## Declaring a Row Matrix

row_mat_1D = np.array([
    1, 3, 2
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 3 2]

Shape:	(3,)
Rank:	1

Matrix:
[[1 2 3]]

Shape:	(1, 3)
Rank:	2



In [ ]:
## Declaring a Column Matrix

col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



##Square Matrices
Matrixes with the same row and column sizes are known as square matrices.
If $I = j$, a matrix is said to be square.
To find square matrices, we can change our matrix descriptor function. 

In [7]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square:{is_square}\n')

In [8]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
     [1,2,5],
     [3,3,8]                       
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square:True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square:False



##Null Matrix
The term "null matrix" refers to a matrix with no elements.
Any vector or matrix is always a subspace of it. 

In [9]:
def describe_mat(matrix):
  if matrix.size < 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square:{is_square}\n')
  else:
    print('Matrix is Null')

In [10]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


##Zero Matrix
A zero matrix can be any rectangular matrix with a value of 0 for all of its entries. 

In [11]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'zero Row Matrix: \n{zero_mat_row}')
print(f'zero Row Matrix: \n{zero_mat_sqr}')
print(f'zero Row Matrix: \n{zero_mat_rct}')

zero Row Matrix: 
[[0. 0.]]
zero Row Matrix: 
[[0. 0.]
 [0. 0.]]
zero Row Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##Ones Matrix
A ones matrix, like a zero matrix, can be any rectangular matrix with 1s instead of 0s in all of its members. 

In [12]:
zero_mat_row = np.ones((1,2))
zero_mat_sqr = np.ones((2,2))
zero_mat_rct = np.ones((3,2))

print(f'zero Row Matrix: \n{zero_mat_row}')
print(f'zero Row Matrix: \n{zero_mat_sqr}')
print(f'zero Row Matrix: \n{zero_mat_rct}')

zero Row Matrix: 
[[1. 1.]]
zero Row Matrix: 
[[1. 1.]
 [1. 1.]]
zero Row Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##Diagonal Matrices
A diagonal matrix is a square matrix that only has values along its diagonal. 

In [13]:
np.array([
      [2,0,0],
      [0,3,0],
      [0,0,5]
])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

##Identity
An identity matrix is a type of diagonal matrix in which the diagonal values are all ones. 

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#Upper Triangular
A matrix with no values below the diagonal is known as an upper triangular matrix. 

In [15]:
np.array([
      [2,1,3],
      [0,3,1],
      [0,0,5]
])

array([[2, 1, 3],
       [0, 3, 1],
       [0, 0, 5]])

##Lower Triangular
A matrix with no values above the diagonal is known as a lower triangular matrix. 

In [33]:
np.array([
      [5,0,0],
      [1,3,0],
      [1,2,3]
])

array([[5, 0, 0],
       [1, 3, 0],
       [1, 2, 3]])

##Practice
1. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix.

$$ A = \left\{\begin{array} 5x_1 + 2x_2 +x_3\\ 4x_2 - x_3\\ 10x_3 \end{array}\right. $$

1. Given the matrix below, express it as a linear combination in a markdown.


In [34]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

1. Given the matrix below, display the output as a LaTeX makdown also express it as a system of linear combinations.

In [35]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

In [36]:
np.array([
    [1, 3, -4]
])


array([[ 1,  3, -4]])

$$



G = \left\{
    \begin{array}\
        x_1 + 7x_2 + 8x_3\\ 
        2x_1 + 2x_2 + 2x_3\\
        4x_1 + 6x_2 + 7_3
    \end{array}
\right.$$

G = \begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7\end{bmatrix}

##Matrix Algebra



**Addition**

In [37]:
A = np.array([
    [1,2],
    [2,3],
    [4,1]
])

B = np.array([
    [2,2],
    [0,0],
    [1,1]          
])

A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [38]:
2+A 

array([[3, 4],
       [4, 5],
       [6, 3]])

In [39]:
2*np.ones(A.shape)+A

array([[3., 4.],
       [4., 5.],
       [6., 3.]])

In [40]:
2*np.ones(A.shape)+A == 2+A 

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

**Subtraction**

In [41]:
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [42]:
3-B

array([[1, 1],
       [3, 3],
       [2, 2]])

##Element Wise Multiplication

In [43]:
A*B

array([[2, 4],
       [0, 0],
       [4, 1]])

In [44]:
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [45]:
A/B

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.5, 1. ],
       [inf, inf],
       [4. , 1. ]])

In [46]:
alpha = 10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])

In [47]:
np.add(A,B)

array([[3, 4],
       [2, 3],
       [5, 2]])

##Activity
**Task 1**
Create a function named mat_desc() that througouhly describes a matrix, it should:




1.   Displays the shape, size, and rank of the matrix
2.   Displays whether the matrix is square or non-square. 
3.   Displays whether the matrix is an empty matrix. 
4.   Displays if the matrix is an identity, ones, or zeros matrix.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.





##Task 1

##Function area

In [49]:
def desc_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

##Matrix Description

In [50]:
## Null Matrix
null_mat = np.array([])

In [51]:
## Zero Matrix
zero_mat_sqr = np.zeros((4,4))

In [52]:
## Ones Matrix
ones_mat_sqr = np.ones((4,4))

In [53]:
## Diagonal Matrix
A = np.array([
    [2, 0, 0],
    [0, 9, 0],
    [0, 0, 5]
])

In [54]:
## Identity Matrix
# np.identity(3)

In [55]:
## Upper Triangular Matrix
B = np.array([
    [2, 3, 4],
    [0, 7, 5],
    [0, 0, 7]
])

In [56]:
#Lower Triangular Matrix
C = np.array([
    [2, 0, 0],
    [9, 7, 0],
    [5, 6, 7]
])

##Test Areas

In [57]:
## Null Matrix
desc_mat(null_mat)

Matrix:
[]

Shape:	(0,)
Rank:	1



In [58]:
## Zero Matrix
desc_mat(zero_mat_sqr)

Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Shape:	(4, 4)
Rank:	2



In [59]:
## Ones Matrix
desc_mat(ones_mat_sqr)

Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Shape:	(4, 4)
Rank:	2



In [60]:
## Diagonal Matrix
desc_mat(A)

Matrix:
[[2 0 0]
 [0 9 0]
 [0 0 5]]

Shape:	(3, 3)
Rank:	2



In [61]:
## Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
## Upper Triangular Matrix
desc_mat(B)

Matrix:
[[2 3 4]
 [0 7 5]
 [0 0 7]]

Shape:	(3, 3)
Rank:	2



In [63]:
#Lower Triangular Matrix
desc_mat(C)

Matrix:
[[2 0 0]
 [9 7 0]
 [5 6 7]]

Shape:	(3, 3)
Rank:	2



###Task 2
Create a function named `mat_operations()` that takes in two matrices a input parameters it should:<br>
 1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
 2. Returns the sum of the matrices.
 3. Returns the differen of the matrices.
 4. Returns the element-wise multiplication of the matrices.
 5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$.
In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.###Task 2

### Task 2

###Function Area

In [64]:
def mat_operations(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

###Matrix Declaration

In [65]:
## Addition
A = np.array([
    [2,4,7],
    [2,3,9],
    [4,3,8]
])
B = np.array([
    [2,4,5],
    [4,2,3],
    [7,8,9]
])

In [66]:
## Subtraction
D = np.array([
    [5,3,4],
    [2,9,7],
    [8,7,1]
])
E = np.array([
    [2,5,6],
    [5,3,7],
    [2,8,9]
])

In [67]:
## element-wise multiplication
F = np.array([
    [4,2,3],
    [3,5,6],
    [7,8,9]
])
G = np.array([
    [3,4,6],
    [2,5,9],
    [1,4,8]
])

In [68]:
## element-wise division
H = np.array([
    [12,13,16],
    [14,18,9],
    [23,19,17]
])
I = np.array([
    [2,7,6],
    [4,4,4],
    [8,9,3]
])

###Test Areas

In [69]:
## Addition
C = A+B
mat_operations(C)

Matrix:
[[ 4  8 12]
 [ 6  5 12]
 [11 11 17]]

Shape:	(3, 3)
Rank:	2



In [70]:
np.add(A,B)

array([[ 4,  8, 12],
       [ 6,  5, 12],
       [11, 11, 17]])

In [71]:
## Subtraction
S = D-E
mat_operations(S)

Matrix:
[[ 3 -2 -2]
 [-3  6  0]
 [ 6 -1 -8]]

Shape:	(3, 3)
Rank:	2



In [72]:
np.subtract(D,E)

array([[ 3, -2, -2],
       [-3,  6,  0],
       [ 6, -1, -8]])

In [73]:
## element-wise multiplication
M = F*G
mat_operations(M)

Matrix:
[[12  8 18]
 [ 6 25 54]
 [ 7 32 72]]

Shape:	(3, 3)
Rank:	2



In [74]:
np.multiply(F,G)

array([[12,  8, 18],
       [ 6, 25, 54],
       [ 7, 32, 72]])

In [75]:
4*G

array([[12, 16, 24],
       [ 8, 20, 36],
       [ 4, 16, 32]])

In [76]:
## element-wise division
V = H/I
mat_operations(V)

Matrix:
[[6.         1.85714286 2.66666667]
 [3.5        4.5        2.25      ]
 [2.875      2.11111111 5.66666667]]

Shape:	(3, 3)
Rank:	2



In [77]:
np.divide(H,I)

array([[6.        , 1.85714286, 2.66666667],
       [3.5       , 4.5       , 2.25      ],
       [2.875     , 2.11111111, 5.66666667]])

In [78]:
H/5

array([[2.4, 2.6, 3.2],
       [2.8, 3.6, 1.8],
       [4.6, 3.8, 3.4]])

In [79]:
1/I

array([[0.5       , 0.14285714, 0.16666667],
       [0.25      , 0.25      , 0.25      ],
       [0.125     , 0.11111111, 0.33333333]])

## Conclusion
In conclusion, in matrix we are presently utilizing is advantageous and incredible in information assortment and mathematical analysis. They are utilized as a method of giving speedy approximations of more muddled computations. In applications, for example, picture preparing and hereditary examination, PCs might increase matrix to address matrices of linear equations. Aside from concurrent equations,the properties of matrices are valuable in programming, where we use an array, which is a matrix to store information. Initially, they were made to depict frameworks of linear equations. PCs can duplicate frameworks to tackle frameworks of direct conditions in applications like picture handling and hereditary exploration. They're utilized to surmised more modern computations rapidly. It is useful for us, ECE students for the future ahead us, because is is for us to have the option to reduce the time we burn-through on one assignment. So, it is extremely useful to make the work simple. 